[package]
name = "microservice"
version = "0.1.0"
authors = ["Michał Pokrywka", "Vlad Ovinnikov"]
edition = "2018"

[features]
default = ["pgsql"]
pgsql = ["diesel", "r2d2", "r2d2-diesel"]
swagger = ["paperclip"]
prometheus = []

[dependencies]
actix-cors = "0.1.0"
actix-http = "0.2.11"
actix-rt = "0.2.6"
actix-service = "0.4.2"
actix-web = "1.0.9"
bytes = "0.4"
chrono = { version = "0.4", features = ["serde"] }
diesel = { version = "1.4", features = ["postgres", "chrono"], optional = true }
dotenv = "0.15"
futures = "0.1"
jsonwebtoken = "7"
log = "0.4"
microservice_derive = { path = "microservice_derive" }
num_cpus = "1"
paperclip = { git = "https://github.com/sfisol/paperclip", branch="legacy-actix-web-1", features = ["actix", "decimal"], optional = true }
r2d2-diesel = { version = "1.0", optional = true }
r2d2 = { version = "0.8", optional = true }
serde = "1.0"
serde_derive = "1.0"
validator = "0.10"
colored = "1.9"
